# Generated by Django 3.2.13 on 2022-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_pk', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('profile_path', models.TextField(null=True)),
                ('gender', models.IntegerField()),
                ('character', models.CharField(max_length=100, null=True)),
                ('popularity', models.IntegerField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.DateTimeField()),
                ('popularity', models.IntegerField()),
                ('vote_avg', models.IntegerField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(related_name='genres', to='movies.Genre')),
            ],
        ),
    ]
